name: release

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - name: Create Tag
        run: |
          go install github.com/caarlos0/svu@latest
          git tag "$(svu p)"
          git push --tags
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
